<?php
require 'ceklogin.php';
require 'function.php';
require_once 'dompdf/autoload.inc.php';

use Dompdf\Dompdf;

// Ambil filter tanggal
$tgl_awal = isset($_GET['tgl_awal']) ? $_GET['tgl_awal'] : date('Y-m-01');
$tgl_akhir = isset($_GET['tgl_akhir']) ? $_GET['tgl_akhir'] : date('Y-m-d');

// Ambil data pesanan
$q = mysqli_query($conn, "SELECT p.idorder, p.tanggal, pl.nama_pelanggan,
    SUM(dp.qty * dp.harga) AS total
    FROM pesanan p 
    JOIN pelanggan pl ON p.idpelanggan = pl.id_pelanggan 
    JOIN detailpesanan dp ON dp.idpesanan = p.idorder 
    WHERE p.tanggal BETWEEN '$tgl_awal' AND '$tgl_akhir' 
    GROUP BY p.idorder 
    ORDER BY p.tanggal DESC");

// Siapkan HTML untuk PDF
$html = "<h2 style='text-align:center;'>LAPORAN PENJUALAN</h2>";
$html .= "<p><strong>Periode:</strong> $tgl_awal s/d $tgl_akhir</p>";
$html .= "<table width='100%' border='1' cellspacing='0' cellpadding='5'>
<thead>
    <tr style='background-color:#f2f2f2;'>
        <th>No</th>
        <th>Tanggal</th>
        <th>Pelanggan</th>
        <th>Total Transaksi</th>
    </tr>
</thead>
<tbody>";

$no = 1;
$grand_total = 0;
while ($row = mysqli_fetch_assoc($q)) {
    $html .= "<tr>
        <td>" . $no++ . "</td>
        <td>" . $row['tanggal'] . "</td>
        <td>" . htmlspecialchars($row['nama_pelanggan']) . "</td>
        <td>Rp" . number_format($row['total']) . "</td>
    </tr>";
    $grand_total += $row['total'];
}
$html .= "<tr>
    <td colspan='3'><strong>Total Penjualan</strong></td>
    <td><strong>Rp" . number_format($grand_total) . "</strong></td>
</tr>";

$html .= "</tbody></table>";
$html .= "<p style='text-align:center;margin-top:30px;'>Generated by Kedai Cemilan Riee</p>";

// Buat PDF
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'landscape');
$dompdf->render();
$dompdf->stream("Laporan_Penjualan_{$tgl_awal}_sd_{$tgl_akhir}.pdf", array("Attachment" => false));
exit;
